name = "QuantumIceBox"
uuid = "07707f98-0760-4715-9a93-38eb460f0166"
authors = ["LongliZheng"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
