name = "QuantumIceBox"
uuid = "07707f98-0760-4715-9a93-38eb460f0166"
version = "1.0.0-DEV"
authors = ["LongliZheng"]

[deps]
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"

[compat]
Yao = "0.9.2"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
